openapi: 3.0.0
info:
  version: 1.0.0
  title: '読書管理アプリ Swagger'
servers:
  - url: http://localhost:3000/api
    description: local
paths:
  /books/:
    get:
      description: '本データ一覧取得 TODO: ヘッダーにユーザ情報付与'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      description: 本データ登録（楽天API使用）
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - isbn
              properties:
                isbn:
                  type: string
                  description: ISBNコード
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /books/self:
    post:
      description: 本データ登録（手動）
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - author
                - publisher
                - status
                - category
                - image_path
              properties:
                name:
                  type: string
                author:
                  type: string
                publisher:
                  type: string
                status:
                  type: integer
                  enum:
                   - 1
                   - 2
                   - 3
                   - 4
                category: 
                  type: integer
                image_path: 
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Book'
            
components:
  schemas:
    Book:
      type: object
      required:
        - ""
      properties:
        id: 
          type: integer
          format: int64
          description: ID
        name:
          type: string
          description: 書籍名
        author:
          type: string
          description: 著者名
        publisher:
          type: string
          description: 出版社
        status:
          type: integer
          description: | 
            読書状態

            1: 未読
            2: 読書中
            3: 読了
            4: 中断
          enum:
            - 1
            - 2
            - 3
            - 4
        category:
          type: string
          description: カテゴリー
        image_path:
          type: string
          description: 画像パス ※楽天APIから取得したパスをそのまま使う想定
        created_at:
          type: string
          description: 追加日
