name: Deploy web source to prod
on:
  push:
    branches:
      - master
    paths:
      - "packages/client/**"
# on: workflow_dispatch
jobs:
  build-push-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Build image & Push assets to s3
        run: |
          DOCKER_BUILDKIT=1 docker build . -t web-prod-assets --target web-production --progress=tty
          docker run -d --name web-prod-assets web-prod-assets:latest sleep 300
          docker cp web-prod-assets:/app/dist /tmp/release
          aws s3 sync /tmp/release s3://bookshelf-web-assets/
